version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    ignore:
      # ignore all bootstrap major updates
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
      # TODO: upgrade iso-8859-2 when ava will have ESM support: https://github.com/orgs/avajs/projects/2
      # https://github.com/FlowCrypt/flowcrypt-browser/pull/3961#issuecomment-921335748
      - dependency-name: "iso-8859-2"
        update-types: ["version-update:semver-major"]
      - dependency-name: "openpgp"
        update-types: ["version-update:semver-major"]
