version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ignore all bootstrap major updates
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
