language: node_js
node_js:
  - "9"
dist: trusty
sudo: false  
addons:
  chrome: stable
before_install:
  - google-chrome-stable --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
    - node_modules
before_script:
 - npm install -g npm@6.2.0
 - npm install -g node@9.4.0
 - npm install -g gulp
 - npm install -g gulp-cli
 - npm install
 - npm install --save-dev @types/jquery@3.3.1
 - openssl aes-256-cbc -K $encrypted_fb782cbdc340_key -iv $encrypted_fb782cbdc340_iv -in test/test-secrets.json.enc -out test/test-secrets.json -d
 - cd test && npm install
script: $TRAVIS_BUILD_DIR/node_modules/gulp-cli/bin/gulp.js test