name: Auto merge

# both actions get started on PR create/update
# approve gets done right away
# merge sleeps and retries until CI finishes successfully up to 25 minutes
# not ideal, much better would be to trigger merge later, exactly whenever CI finishes. But couldn't make make it work.

# Trigger the workflow on pull request
on:
  pull_request_target:
    types:
      - synchronize
      - opened

jobs:

  autoapprove:
    name: Approve
    runs-on: ubuntu-latest # Environment on which the job runs
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0 # Custom action for auto approval already available on marketplace
        # Perform the auto approve action only when the PR is raised by dependabot
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          # Create a personal access token and store it under the Secrets section of the particular repository
          # with the key "GITHUB_ACTIONS_TOKEN"
          github-token: ${{ secrets.FLOWCRYPT_ROBOT_ACCESS_TOKEN }}

  automerge:
    name: Merge
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        # Custom action for auto merging already available on marketplace
        uses: pascalgn/automerge-action@v0.13.0
        # Perform the auto merge action only when the PR is raised by dependabot
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.FLOWCRYPT_ROBOT_ACCESS_TOKEN }}
          # By default, whenever dependabot raises a PR, it automatically assigns a label named "dependencies"
          # So, this action merges those PRs labelled "dependencies" only
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
          MERGE_FILTER_AUTHOR: 'dependabot[bot]'
          MERGE_RETRIES: 50
          MERGE_RETRY_SLEEP: 30000
